function par = processConfig(config, conv)
%processConfig processes the configuration file to derive important
%parameters and convert every input to SI units
%   
% Inputs:
%   par     (struct)  	parameters generated by a configuration file
%   *conv   (bool)      0 = one (default) / 
%
% Outputs:
%   par     (struct)  	parameters in SI units and additional derivations
% 
% Usage:
%   run a config fle based on the 'config_example.m' model
%   the user may define here derived parameters
%   
%
%   example:
%       to recompute SI units SFC after change
%       >> config = config_example();
%       ...
%       >> config.SFC = 0.7;
%       >> par.processConfig(config);
%
% Calls: -
%

% Optional argument
if nargin == 1
    conv = 1;
end

% Unit conversions
if conv == 1
par.SFC = config.SFC / 36000 * 10; % h -> s and daN -> N
par.T = config.T / 0.44822; % lbf -> N
end

% New derived parameters


end

